### ISSUE TITLE
Keyboard input messed up (in VICE)

### ISSUE THREAD

**Issue by SvenMichaelKlose** [ytmytm/c64-lng#2]
Just compiled it on some Linux.

Cannot get a '/' to boot it. Also it seems like the SHIFT key has to be released before pressing the next key with it down.

Amazing stuff... 8)

**Comment by ytmytm** [comment]
If you do "make disc" or "make cbmdisk" you will get a D64 file with all apps and modules that can be autostarted in VICE.
It runs the .lunixrc init script and leaves you in the shell with "#" prompt.

I just tried it and it seems to be working fine - a little less responsive than it should with tasks running in the background, but no problems with SHIFT whatsoever.

**Comment by SvenMichaelKlose** [comment]
Thanks! Found out what was wrong: it takes "true drive emulation" and keyboard set to "positional" in VICE. 8)
