### ISSUE TITLE
[0001] unhandled: no such file

### ISSUE THREAD

**Issue by pedrouran** [ytmytm/c64-lng#6]
Hello,

I am testing the installation using VICE. I have copyed all self extracting .C64 files into a blank disk.

I typed LOAD"CORE.64",8

It extracted all files, and then I typed: LOAD "LOADER",8,1

And I got this error:
![image](https://github.com/ytmytm/c64-lng/assets/68319897/73b0c613-abb6-41e1-82a7-57b0c6ccf6f1)

This is the disk extracted:
![image](https://github.com/ytmytm/c64-lng/assets/68319897/8e4664c4-0031-4cfa-93e0-497f2fe10d91)

**Comment by ytmytm** [comment]
You are in microshell (`.` prompt). It tried to load `sh` shell but failed. 
You have to load and run the `APPS.C64` to extract system tools too.

**Comment by pedrouran** [comment]
Thank you very much for your response. Thats it, I needed to extract APPS.C64. Now it is working.

![image](https://github.com/ytmytm/c64-lng/assets/68319897/522d3bd6-31df-4115-8b1a-6e7112af3bbc)
